lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '70c63249db6b642fbecf1b4c19e70ec300f9d2a32df6cee80b5b69f6b138dd5b'
    token_ttl: 3600