<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241011190335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE association_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE charge_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE decede_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE demande_financier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE demande_materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE donation_financier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE donnation_materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE enfant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE evenement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE genre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE import_membre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mariage_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE payement_cotisation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personne_membre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personne_membre_profession_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE prix_charge_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE prix_cotisation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE profession_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE quitte_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refuser_demande_financier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refuser_demande_materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE role_suspendu_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sortie_caisse_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE suivis_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tresoreri_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_depense_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_evenement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_revenu_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE validation_demande_financier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE validation_demande_materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE vallee_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE versement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE village_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE association (id INT NOT NULL, nom VARCHAR(200) NOT NULL, siege VARCHAR(200) NOT NULL, date_creation DATE NOT NULL, description VARCHAR(500) NOT NULL, email VARCHAR(500) DEFAULT NULL, telephone VARCHAR(16) DEFAULT NULL, secteur_activite VARCHAR(500) NOT NULL, nature_juridique VARCHAR(500) NOT NULL, slogan VARCHAR(500) DEFAULT NULL, logo VARCHAR(500) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_materiel (id INT NOT NULL, nom_categorie VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE charge (id INT NOT NULL, nom_charge VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE decede (id INT NOT NULL, id_personne_membre_id INT NOT NULL, date_dece DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_28B37E80EFCE22FB ON decede (id_personne_membre_id)');
        $this->addSql('CREATE TABLE demande_financier (id INT NOT NULL, id_personne_membre_id INT NOT NULL, date_demande_financier DATE NOT NULL, montant DOUBLE PRECISION NOT NULL, motif VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_85CFA81EEFCE22FB ON demande_financier (id_personne_membre_id)');
        $this->addSql('CREATE TABLE demande_materiel (id INT NOT NULL, id_personne_membre_id INT NOT NULL, id_materiel_id INT NOT NULL, nombre INT NOT NULL, date_de_demande DATE NOT NULL, motif VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E8BF953EFCE22FB ON demande_materiel (id_personne_membre_id)');
        $this->addSql('CREATE INDEX IDX_5E8BF953E9AC758 ON demande_materiel (id_materiel_id)');
        $this->addSql('CREATE TABLE donation_financier (id INT NOT NULL, id_utilisateur_id INT NOT NULL, nom_donation_financier VARCHAR(200) NOT NULL, date_donation_financier DATE NOT NULL, montant DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A02D68E8C6EE5C49 ON donation_financier (id_utilisateur_id)');
        $this->addSql('CREATE TABLE donnation_materiel (id INT NOT NULL, id_materiel_id INT NOT NULL, id_utilisateur_id_id INT NOT NULL, nom_donnateur_materiel VARCHAR(500) DEFAULT NULL, date_acquisition DATE NOT NULL, nombre INT NOT NULL, image VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8AEC0BCCE9AC758 ON donnation_materiel (id_materiel_id)');
        $this->addSql('CREATE INDEX IDX_8AEC0BCC48B6AE9E ON donnation_materiel (id_utilisateur_id_id)');
        $this->addSql('CREATE TABLE enfant (id INT NOT NULL, id_enfant_id INT NOT NULL, id_mariage_parent_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_34B70CA2C538990E ON enfant (id_enfant_id)');
        $this->addSql('CREATE INDEX IDX_34B70CA230BBD5C9 ON enfant (id_mariage_parent_id)');
        $this->addSql('CREATE TABLE evenement (id INT NOT NULL, id_utilisateur_id INT NOT NULL, id_type_evenement_id INT NOT NULL, id_association_id INT NOT NULL, description_evenement VARCHAR(500) NOT NULL, date_publication DATE NOT NULL, date_evenement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin_evenement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu_evenement VARCHAR(500) NOT NULL, nom VARCHAR(255) NOT NULL, publier BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B26681EC6EE5C49 ON evenement (id_utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_B26681E79A4FD01 ON evenement (id_type_evenement_id)');
        $this->addSql('CREATE INDEX IDX_B26681ED2DF75A3 ON evenement (id_association_id)');
        $this->addSql('CREATE TABLE genre (id INT NOT NULL, nom_genre VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE import_membre (id INT NOT NULL, anarana VARCHAR(255) NOT NULL, fanampiny VARCHAR(255) NOT NULL, daty_naterahana VARCHAR(255) NOT NULL, lahy_na_vavy VARCHAR(255) NOT NULL, adiresy_eto_antananarivo VARCHAR(255) NOT NULL, trangobe VARCHAR(255) NOT NULL, fiaviana_antanana VARCHAR(255) NOT NULL, laharana_finday VARCHAR(255) NOT NULL, mailaka VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE mariage (id INT NOT NULL, id_mari_id INT NOT NULL, id_marie_id INT NOT NULL, date_mariage DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FE8EC22360490D0 ON mariage (id_mari_id)');
        $this->addSql('CREATE INDEX IDX_2FE8EC2214E66322 ON mariage (id_marie_id)');
        $this->addSql('CREATE TABLE materiel (id INT NOT NULL, id_categorie_materiel_id INT NOT NULL, nom_materiel VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_18D2B09118C1BBA6 ON materiel (id_categorie_materiel_id)');
        $this->addSql('CREATE TABLE payement_cotisation (id INT NOT NULL, id_utilisateur_id INT NOT NULL, id_personne_membre_id INT NOT NULL, date_de_payement DATE NOT NULL, montant_cotisation_total_payer DOUBLE PRECISION NOT NULL, date_payer DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FFA2560C6EE5C49 ON payement_cotisation (id_utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_2FFA2560EFCE22FB ON payement_cotisation (id_personne_membre_id)');
        $this->addSql('CREATE TABLE personne_membre (id INT NOT NULL, id_village_id INT NOT NULL, id_genre_id INT NOT NULL, nom_membre VARCHAR(500) NOT NULL, date_de_naissance DATE NOT NULL, address VARCHAR(500) NOT NULL, email VARCHAR(5000) NOT NULL, telephone VARCHAR(500) NOT NULL, prenom_membre VARCHAR(500) NOT NULL, date_inscription DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C2CEC3C4FB87D555 ON personne_membre (id_village_id)');
        $this->addSql('CREATE INDEX IDX_C2CEC3C4124D3F8A ON personne_membre (id_genre_id)');
        $this->addSql('CREATE TABLE personne_membre_profession (id INT NOT NULL, id_personne_membre_id INT NOT NULL, id_profession_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_13A68FD1EFCE22FB ON personne_membre_profession (id_personne_membre_id)');
        $this->addSql('CREATE INDEX IDX_13A68FD143C758F3 ON personne_membre_profession (id_profession_id)');
        $this->addSql('CREATE TABLE prix_charge (id INT NOT NULL, id_charge_id INT NOT NULL, valeur DOUBLE PRECISION NOT NULL, date_insertion_prix_charge DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D95897A9D51DF533 ON prix_charge (id_charge_id)');
        $this->addSql('CREATE TABLE prix_cotisation (id INT NOT NULL, id_utilisateur_id INT NOT NULL, valeur DOUBLE PRECISION NOT NULL, date_modif DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D7061A66C6EE5C49 ON prix_cotisation (id_utilisateur_id)');
        $this->addSql('CREATE TABLE profession (id INT NOT NULL, nom_profession VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE quitte (id INT NOT NULL, id_personne_membre_id INT NOT NULL, date DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_23D34158EFCE22FB ON quitte (id_personne_membre_id)');
        $this->addSql('CREATE TABLE refuser_demande_financier (id INT NOT NULL, id_demande_financier_id INT NOT NULL, id_utilisateur_id INT NOT NULL, dates DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2588E029110C53AB ON refuser_demande_financier (id_demande_financier_id)');
        $this->addSql('CREATE INDEX IDX_2588E029C6EE5C49 ON refuser_demande_financier (id_utilisateur_id)');
        $this->addSql('CREATE TABLE refuser_demande_materiel (id INT NOT NULL, id_demande_materiel_id INT NOT NULL, id_utilisateur_id INT NOT NULL, dates DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1321B6B3F145C910 ON refuser_demande_materiel (id_demande_materiel_id)');
        $this->addSql('CREATE INDEX IDX_1321B6B3C6EE5C49 ON refuser_demande_materiel (id_utilisateur_id)');
        $this->addSql('CREATE TABLE role (id INT NOT NULL, nom_role VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE role_suspendu (id INT NOT NULL, id_admin_id INT NOT NULL, date_suspension DATE NOT NULL, date_fin_suspension DATE NOT NULL, role VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C855050C34F06E85 ON role_suspendu (id_admin_id)');
        $this->addSql('CREATE TABLE sortie_caisse (id INT NOT NULL, id_utilisateur_id INT NOT NULL, id_type_depence_id INT NOT NULL, date_sortie_caisse DATE NOT NULL, montant DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B5579974C6EE5C49 ON sortie_caisse (id_utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_B5579974D565974C ON sortie_caisse (id_type_depence_id)');
        $this->addSql('CREATE TABLE suivis (id INT NOT NULL, administrateur_id_id INT NOT NULL, utilisateur_id_id INT NOT NULL, date_attribution DATE NOT NULL, role VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6627ED706B298048 ON suivis (administrateur_id_id)');
        $this->addSql('CREATE INDEX IDX_6627ED70B981C689 ON suivis (utilisateur_id_id)');
        $this->addSql('CREATE TABLE tresoreri (id INT NOT NULL, montant DOUBLE PRECISION NOT NULL, date_tresoreri TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_depense (id INT NOT NULL, motif_depense VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_evenement (id INT NOT NULL, nom_type_evenement VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_revenu (id INT NOT NULL, motif_revenu VARCHAR(500) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE users (id INT NOT NULL, id_personne_id INT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9BA091CE5 ON users (id_personne_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON users (username)');
        $this->addSql('CREATE TABLE validation_demande_financier (id INT NOT NULL, id_demande_financier_id INT DEFAULT NULL, id_utilisateur_id INT NOT NULL, date_validation DATE NOT NULL, montant DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C2692248110C53AB ON validation_demande_financier (id_demande_financier_id)');
        $this->addSql('CREATE INDEX IDX_C2692248C6EE5C49 ON validation_demande_financier (id_utilisateur_id)');
        $this->addSql('CREATE TABLE validation_demande_materiel (id INT NOT NULL, id_utilisateur_id INT NOT NULL, id_demande_materiel_id INT NOT NULL, date_de_validation DATE NOT NULL, nombre INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4ACED0BDC6EE5C49 ON validation_demande_materiel (id_utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_4ACED0BDF145C910 ON validation_demande_materiel (id_demande_materiel_id)');
        $this->addSql('CREATE TABLE vallee (id INT NOT NULL, nom_vallee VARCHAR(200) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE versement (id INT NOT NULL, id_utilisateur_id INT NOT NULL, id_revenu_id INT NOT NULL, date_versement DATE NOT NULL, montant DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_716E9367C6EE5C49 ON versement (id_utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_716E93671400135D ON versement (id_revenu_id)');
        $this->addSql('CREATE TABLE village (id INT NOT NULL, id_vallee_id INT NOT NULL, nom_village VARCHAR(200) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4E6C7FAAECEB86D ON village (id_vallee_id)');
        $this->addSql('ALTER TABLE decede ADD CONSTRAINT FK_28B37E80EFCE22FB FOREIGN KEY (id_personne_membre_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE demande_financier ADD CONSTRAINT FK_85CFA81EEFCE22FB FOREIGN KEY (id_personne_membre_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE demande_materiel ADD CONSTRAINT FK_5E8BF953EFCE22FB FOREIGN KEY (id_personne_membre_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE demande_materiel ADD CONSTRAINT FK_5E8BF953E9AC758 FOREIGN KEY (id_materiel_id) REFERENCES materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE donation_financier ADD CONSTRAINT FK_A02D68E8C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE donnation_materiel ADD CONSTRAINT FK_8AEC0BCCE9AC758 FOREIGN KEY (id_materiel_id) REFERENCES materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE donnation_materiel ADD CONSTRAINT FK_8AEC0BCC48B6AE9E FOREIGN KEY (id_utilisateur_id_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE enfant ADD CONSTRAINT FK_34B70CA2C538990E FOREIGN KEY (id_enfant_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE enfant ADD CONSTRAINT FK_34B70CA230BBD5C9 FOREIGN KEY (id_mariage_parent_id) REFERENCES mariage (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681EC6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681E79A4FD01 FOREIGN KEY (id_type_evenement_id) REFERENCES type_evenement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681ED2DF75A3 FOREIGN KEY (id_association_id) REFERENCES association (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mariage ADD CONSTRAINT FK_2FE8EC22360490D0 FOREIGN KEY (id_mari_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mariage ADD CONSTRAINT FK_2FE8EC2214E66322 FOREIGN KEY (id_marie_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE materiel ADD CONSTRAINT FK_18D2B09118C1BBA6 FOREIGN KEY (id_categorie_materiel_id) REFERENCES categorie_materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payement_cotisation ADD CONSTRAINT FK_2FFA2560C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payement_cotisation ADD CONSTRAINT FK_2FFA2560EFCE22FB FOREIGN KEY (id_personne_membre_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_membre ADD CONSTRAINT FK_C2CEC3C4FB87D555 FOREIGN KEY (id_village_id) REFERENCES village (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_membre ADD CONSTRAINT FK_C2CEC3C4124D3F8A FOREIGN KEY (id_genre_id) REFERENCES genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_membre_profession ADD CONSTRAINT FK_13A68FD1EFCE22FB FOREIGN KEY (id_personne_membre_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_membre_profession ADD CONSTRAINT FK_13A68FD143C758F3 FOREIGN KEY (id_profession_id) REFERENCES profession (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prix_charge ADD CONSTRAINT FK_D95897A9D51DF533 FOREIGN KEY (id_charge_id) REFERENCES charge (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prix_cotisation ADD CONSTRAINT FK_D7061A66C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quitte ADD CONSTRAINT FK_23D34158EFCE22FB FOREIGN KEY (id_personne_membre_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refuser_demande_financier ADD CONSTRAINT FK_2588E029110C53AB FOREIGN KEY (id_demande_financier_id) REFERENCES demande_financier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refuser_demande_financier ADD CONSTRAINT FK_2588E029C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refuser_demande_materiel ADD CONSTRAINT FK_1321B6B3F145C910 FOREIGN KEY (id_demande_materiel_id) REFERENCES demande_materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refuser_demande_materiel ADD CONSTRAINT FK_1321B6B3C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_suspendu ADD CONSTRAINT FK_C855050C34F06E85 FOREIGN KEY (id_admin_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sortie_caisse ADD CONSTRAINT FK_B5579974C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sortie_caisse ADD CONSTRAINT FK_B5579974D565974C FOREIGN KEY (id_type_depence_id) REFERENCES type_depense (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE suivis ADD CONSTRAINT FK_6627ED706B298048 FOREIGN KEY (administrateur_id_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE suivis ADD CONSTRAINT FK_6627ED70B981C689 FOREIGN KEY (utilisateur_id_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9BA091CE5 FOREIGN KEY (id_personne_id) REFERENCES personne_membre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE validation_demande_financier ADD CONSTRAINT FK_C2692248110C53AB FOREIGN KEY (id_demande_financier_id) REFERENCES demande_financier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE validation_demande_financier ADD CONSTRAINT FK_C2692248C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE validation_demande_materiel ADD CONSTRAINT FK_4ACED0BDC6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE validation_demande_materiel ADD CONSTRAINT FK_4ACED0BDF145C910 FOREIGN KEY (id_demande_materiel_id) REFERENCES demande_materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE versement ADD CONSTRAINT FK_716E9367C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE versement ADD CONSTRAINT FK_716E93671400135D FOREIGN KEY (id_revenu_id) REFERENCES type_revenu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE village ADD CONSTRAINT FK_4E6C7FAAECEB86D FOREIGN KEY (id_vallee_id) REFERENCES vallee (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE association_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE charge_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE decede_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE demande_financier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE demande_materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE donation_financier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE donnation_materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE enfant_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE evenement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE genre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE import_membre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mariage_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE payement_cotisation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personne_membre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personne_membre_profession_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE prix_charge_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE prix_cotisation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE profession_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE quitte_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refuser_demande_financier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refuser_demande_materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE role_suspendu_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sortie_caisse_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE suivis_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tresoreri_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_depense_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_evenement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_revenu_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE users_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE validation_demande_financier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE validation_demande_materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE vallee_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE versement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE village_id_seq CASCADE');
        $this->addSql('ALTER TABLE decede DROP CONSTRAINT FK_28B37E80EFCE22FB');
        $this->addSql('ALTER TABLE demande_financier DROP CONSTRAINT FK_85CFA81EEFCE22FB');
        $this->addSql('ALTER TABLE demande_materiel DROP CONSTRAINT FK_5E8BF953EFCE22FB');
        $this->addSql('ALTER TABLE demande_materiel DROP CONSTRAINT FK_5E8BF953E9AC758');
        $this->addSql('ALTER TABLE donation_financier DROP CONSTRAINT FK_A02D68E8C6EE5C49');
        $this->addSql('ALTER TABLE donnation_materiel DROP CONSTRAINT FK_8AEC0BCCE9AC758');
        $this->addSql('ALTER TABLE donnation_materiel DROP CONSTRAINT FK_8AEC0BCC48B6AE9E');
        $this->addSql('ALTER TABLE enfant DROP CONSTRAINT FK_34B70CA2C538990E');
        $this->addSql('ALTER TABLE enfant DROP CONSTRAINT FK_34B70CA230BBD5C9');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681EC6EE5C49');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681E79A4FD01');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681ED2DF75A3');
        $this->addSql('ALTER TABLE mariage DROP CONSTRAINT FK_2FE8EC22360490D0');
        $this->addSql('ALTER TABLE mariage DROP CONSTRAINT FK_2FE8EC2214E66322');
        $this->addSql('ALTER TABLE materiel DROP CONSTRAINT FK_18D2B09118C1BBA6');
        $this->addSql('ALTER TABLE payement_cotisation DROP CONSTRAINT FK_2FFA2560C6EE5C49');
        $this->addSql('ALTER TABLE payement_cotisation DROP CONSTRAINT FK_2FFA2560EFCE22FB');
        $this->addSql('ALTER TABLE personne_membre DROP CONSTRAINT FK_C2CEC3C4FB87D555');
        $this->addSql('ALTER TABLE personne_membre DROP CONSTRAINT FK_C2CEC3C4124D3F8A');
        $this->addSql('ALTER TABLE personne_membre_profession DROP CONSTRAINT FK_13A68FD1EFCE22FB');
        $this->addSql('ALTER TABLE personne_membre_profession DROP CONSTRAINT FK_13A68FD143C758F3');
        $this->addSql('ALTER TABLE prix_charge DROP CONSTRAINT FK_D95897A9D51DF533');
        $this->addSql('ALTER TABLE prix_cotisation DROP CONSTRAINT FK_D7061A66C6EE5C49');
        $this->addSql('ALTER TABLE quitte DROP CONSTRAINT FK_23D34158EFCE22FB');
        $this->addSql('ALTER TABLE refuser_demande_financier DROP CONSTRAINT FK_2588E029110C53AB');
        $this->addSql('ALTER TABLE refuser_demande_financier DROP CONSTRAINT FK_2588E029C6EE5C49');
        $this->addSql('ALTER TABLE refuser_demande_materiel DROP CONSTRAINT FK_1321B6B3F145C910');
        $this->addSql('ALTER TABLE refuser_demande_materiel DROP CONSTRAINT FK_1321B6B3C6EE5C49');
        $this->addSql('ALTER TABLE role_suspendu DROP CONSTRAINT FK_C855050C34F06E85');
        $this->addSql('ALTER TABLE sortie_caisse DROP CONSTRAINT FK_B5579974C6EE5C49');
        $this->addSql('ALTER TABLE sortie_caisse DROP CONSTRAINT FK_B5579974D565974C');
        $this->addSql('ALTER TABLE suivis DROP CONSTRAINT FK_6627ED706B298048');
        $this->addSql('ALTER TABLE suivis DROP CONSTRAINT FK_6627ED70B981C689');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9BA091CE5');
        $this->addSql('ALTER TABLE validation_demande_financier DROP CONSTRAINT FK_C2692248110C53AB');
        $this->addSql('ALTER TABLE validation_demande_financier DROP CONSTRAINT FK_C2692248C6EE5C49');
        $this->addSql('ALTER TABLE validation_demande_materiel DROP CONSTRAINT FK_4ACED0BDC6EE5C49');
        $this->addSql('ALTER TABLE validation_demande_materiel DROP CONSTRAINT FK_4ACED0BDF145C910');
        $this->addSql('ALTER TABLE versement DROP CONSTRAINT FK_716E9367C6EE5C49');
        $this->addSql('ALTER TABLE versement DROP CONSTRAINT FK_716E93671400135D');
        $this->addSql('ALTER TABLE village DROP CONSTRAINT FK_4E6C7FAAECEB86D');
        $this->addSql('DROP TABLE association');
        $this->addSql('DROP TABLE categorie_materiel');
        $this->addSql('DROP TABLE charge');
        $this->addSql('DROP TABLE decede');
        $this->addSql('DROP TABLE demande_financier');
        $this->addSql('DROP TABLE demande_materiel');
        $this->addSql('DROP TABLE donation_financier');
        $this->addSql('DROP TABLE donnation_materiel');
        $this->addSql('DROP TABLE enfant');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE import_membre');
        $this->addSql('DROP TABLE mariage');
        $this->addSql('DROP TABLE materiel');
        $this->addSql('DROP TABLE payement_cotisation');
        $this->addSql('DROP TABLE personne_membre');
        $this->addSql('DROP TABLE personne_membre_profession');
        $this->addSql('DROP TABLE prix_charge');
        $this->addSql('DROP TABLE prix_cotisation');
        $this->addSql('DROP TABLE profession');
        $this->addSql('DROP TABLE quitte');
        $this->addSql('DROP TABLE refuser_demande_financier');
        $this->addSql('DROP TABLE refuser_demande_materiel');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_suspendu');
        $this->addSql('DROP TABLE sortie_caisse');
        $this->addSql('DROP TABLE suivis');
        $this->addSql('DROP TABLE tresoreri');
        $this->addSql('DROP TABLE type_depense');
        $this->addSql('DROP TABLE type_evenement');
        $this->addSql('DROP TABLE type_revenu');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE validation_demande_financier');
        $this->addSql('DROP TABLE validation_demande_materiel');
        $this->addSql('DROP TABLE vallee');
        $this->addSql('DROP TABLE versement');
        $this->addSql('DROP TABLE village');
    }
}
